# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4cebb6554ca1f0f145c70ef85e83b9875e69775a559e4dde88c1c5a1109bae663bb11c8cc095de97ff042bc2df509e8addb0e6f75484ae5cc1747e0315e8dd69

test:
  secret_key_base: 60c5f9cdb56375be7f3eeae720203870144dcf1aabaa89085aa5cd058f579db6123cc39ce56df638addee2da79d2e56cc15b67251ddaa81e61713f70e67c2787

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
